name: Single Runner
on:
    workflow_dispatch:
jobs:
    download:
        runs-on: ubuntu-latest
        steps:
            - name: Runner
              run: |
                  sudo apt update -y
                  sudo apt install openssl shellinabox openssh-client
                  sudo systemctl restart shellinabox
                  sudo apt install wget
                  wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
                  whoami
                  id
                  mkdir ~/.ssh
                  ls -la ~/.ssh
                  chmod 700 ~/.ssh
                  ls -la ~/.ssh
                  touch ~/.ssh/authorized_keys
                  ls -la ~/.ssh
                  chmod 600 ~/.ssh/authorized_keys
                  ls -la ~/.ssh
                  echo ${{ secrets.RSA }}
                  echo ${{ secrets.RSA }} >> ~/.ssh/authorized_keys                  
                  sudo apt install ./cloudflared-linux-amd64.deb
                  sudo ss -tupln 
                  sudo cloudflared service install ${{ secrets.CLOUDFLARE }}
                  wget https://raw.githubusercontent.com/trickest/resolvers/main/resolvers.txt 
                  git clone https://github.com/shantanu561993/Certificate-Transparency-Monitor---Rust.git -b dirty
                  git clone https://github.com/zmap/zdns.git
                  cd zdns
                  go build
                  cd ../Certificate-Transparency-Monitor---Rust
                  cargo build --release 
                  Certificate-Transparency-Monitor---Rust/target/release/ctlrust  | zdns/zdns CNAME --name-servers @resolvers.txt | jq -r 'if .data.answers then (.data.answers[] | {answer, name}) else empty end'
                  sudo shellinaboxd --port 7777 --debug --disable-ssl --service /:${USER}:${USER}:${PWD}:bash
                  
